src/utils/theme.jsx

colors style

---

package-lock.json
package.json
src/components/App.jsx
src/components/RecipeCard/Recipecard.jsx
src/components/RecipeCard/Recipecard.styled.js
src/pages/Categories/Axios/AxiosGetCategories.js
src/pages/Categories/Axios/AxiosGetResieptsFromCategory.js
src/pages/Categories/CategoriesPage.jsx
src/pages/Categories/Styled/CategoriesList.styled.js
src/pages/Categories/Styled/CategoriesListItem.styled.js
src/pages/Categories/Styled/CategoriesPage.styled.js
src/pages/Categories/Styled/CategoriesTable.styled.js
src/pages/Categories/Styled/test.styled.js
src/pages/Categories/index.js

Ще в процесі. 
В Арр додав щоб бачити своє.

Category add

---

src/components/ButtonDelete/ButtonDelete.jsx
src/components/ButtonDelete/index.js

Конфликтов не должно быть, работала в новом компоненте

ButtonDelete

---

src/components/App.jsx
src/components/SearchForm/SearchForm.jsx

Додав сторінку SearchPage до роуту в App

Import SearchPage to App

---

src/components/NavLinkSkew/NavLinkSkew.jsx
src/components/NavLinkSkew/NavLinkSkew.styled.js
src/components/NavLinkSkew/index.js
src/utils/theme.jsx

Сделала линк компонент, можно переиспользовать (по сути косая зеленая кнопка на странице Favorites, Search, My recipes.

Link component See recipe

---

package-lock.json
src/components/RecipePageHero/RecipePageHero.jsx
src/pages/RecipePage/RecipePage.jsx

Recipe page1

---

src/components/ButtonSkew/ButtonSkew.jsx
src/components/ButtonSkew/buttonSkew.styled.jsx
src/components/ButtonSkew/index.js
src/components/RecipePageHero/RecipePageHero.jsx
src/components/RecipePageHero/RecipePageHero.styled.js

add component ButtonSkew and add it in components ResipePageHero

Recipe page hero

---

src/components/Container/Container.styled.jsx
src/components/RecipesList/RecipesList.styled.jsx
src/components/SearchForm/SearchForm.styled.jsx

Recipe item styles

---

src/components/App.jsx
src/pages/MyRecipes/MyRecipesPage.jsx

Add page to App

---

src/components/MyRecipesItem/MyRecipesItem.jsx
src/components/MyRecipesItem/MyRecipesItem.styled.jsx
src/components/MyRecipesList/MyRecipesList.jsx
src/pages/MyRecipes/MyRecipesPage.jsx

Робота над компонентами та стилями

Markup&styles

---

package-lock.json
package.json
src/components/Loader/Loader.jsx
src/pages/FavoritePage/FavoritePage.jsx

Loader v1.

---

src/components/RecipesList/RecipesList.jsx
src/components/SearchedRecipesList/SearchedRecipesList.jsx
src/pages/Search/SearchPage.jsx
src/redux/outerRecipes/outerRecipesSlice.js
src/service/API/TheMealAPI.js

Get data by search

---

src/components/BurgerButtonMenu/BurgerButton.jsx
src/components/Header/Header.jsx
src/components/Header/Header.styled.jsx
src/components/modal/Modal.jsx
src/components/modal/Modal.styled.jsx
src/components/modal/index.jsx
src/hooks/index.js
src/hooks/useMedia.js

correct header and modalburger

correct header and modalburger

---

src/pages/Main/MainSection.jsx
src/pages/Main/Search/SearchMain.jsx

add fix name

---

src/components/Header/Header.jsx
src/components/Header/Header.styled.jsx
src/components/Logo/Logo.jsx
src/components/User/UserLogo/UserLogo.jsx
src/components/User/UserLogo/UserLogo.styled.js

Styled for user-container-header

userContainer

---

src/components/SearchBar/SearchBar.jsx
src/components/SearchForm/SearchForm.jsx
src/components/SearchForm/SearchForm.styled.jsx
src/components/SearchedRecipesList/SearchedRecipesList.jsx
src/pages/Search/SearchPage.jsx
src/redux/search/searchOperations.js
src/redux/search/searchSelectors.js
src/redux/search/searchSlice.js

Add Loader&toast, fix reducer, fix api

---

src/components/BurgerButtonMenu/BurgerButton.jsx
src/components/BurgerButtonMenu/BurgerButton.styled.jsx
src/components/BurgerMenu/BurgerMenu.jsx
src/components/BurgerMenu/BurgerMenu.styled.jsx

fix headerBurger styles

---

src/components/RecipeCard/Recipecard.styled.js
src/components/Title/Title.styled.jsx
src/pages/Categories/Styled/CategoriesTable.styled.js

This reverts commit a4b02c40a0dd3743e3dbd9b26f00217e1118f068, reversing changes made to 2bc886cf118330e6a3e374b735a30026a2992a38.

Revert "Merge pull request #112 from jrudenko/categoryTheme"

---

src/components/AuthForm/RegistrationForm.jsx
src/components/Loader/Loader.jsx

Повернення блудного лоадеру з правильним розміром )

original fix loader )

---

src/components/BurgerButtonMenu/BurgerButton.jsx
src/components/BurgerButtonMenu/BurgerButton.styled.jsx
src/components/BurgerMenu/BurgerMenu.jsx
src/components/BurgerMenu/BurgerMenu.styled.jsx
src/components/Header/Header.styled.jsx
src/components/Logo/Logo.jsx
src/components/Navigation/Navigation.styled.jsx
src/components/ThemeToggler/ThemeToggler.styled.jsx

fixed the completeness of the header

fix header

---

src/components/Navigation/Navigation.jsx
src/components/Navigation/Navigation.styled.jsx

Пофіксила навігацію на сторінці рецептів для темної теми

fix navigation recipe styled

---

src/components/App.jsx
src/pages/Registration/RegistrationPage.styled.js

Стилізував Toastify під наші стилі.

styled Toastify

---

src/components/AddRecipeForm/AddRecipeForm.jsx
src/components/AddRecipeForm/RecipeDescriptionFields/RecipeDescriptionFields.jsx
src/redux/addRecipe/addRecipeOperation.js

create add recipe

---

src/components/Header/Header.styled.jsx
src/components/RecipeInngredientsList/RecipeInngredientsList.jsx
src/components/RecipePageHero/RecipePageHero.styled.js
src/components/ShoppingList/ShoppingList.jsx
src/components/ShoppingList/ShoppingList.styled.js
src/components/ShoppingList/ShoppingListItem.jsx
src/pages/ShoppingPage/ShoppingPage.js
src/redux/shoppingList/shoppingListSlice.js

Пофіксив RecipeHero стилі і ShoppingPage пофіксив помилки, написав логіку видалення інгрідієнта, кого це таска?, там треба стилі доробити.

fix Hero and ShoppingPage

---

src/pages/Main/PreviewCategories/Preview/CategotyCard.jsx
src/pages/Main/PreviewCategories/PreviewCategories.jsx

removed functions that were not used

clear PreviewCategories

---

src/components/App.jsx
src/components/BtnScrollToTop/BtnScrollToTop.jsx
src/components/BtnScrollToTop/BtnScrollToTop.styled.jsx
src/components/BurgerMenu/BurgerMenu.jsx
src/components/BurgerMenu/BurgerMenu.styled.jsx
src/components/Header/Header.jsx
src/components/Navigation/Navigation.styled.jsx
src/components/SharedLayout/SharedLayout.jsx
src/utils/theme.jsx

Стилі навігації. Кнопка скролу вверх

Navigation

---

src/components/BtnScrollToTop/BtnScrollToTop.styled.jsx
src/components/BurgerMenu/BurgerMenu.jsx

Лого в бургері вже переходить на головну

fix LogoBurger

---

src/components/RecipePageHero/RecipePageHero.jsx
src/components/RecipePreparation/RecipePreparation.jsx
src/pages/RecipePage/RecipePage.jsx

fix recipe

---

src/components/BurgerMenu/BurgerMenu.jsx

fix burgermenu

---

src/pages/SingIn/SinginPage.jsx
src/redux/auth/operations.js
src/redux/search/searchOperations.js
src/service/API/getCategoryList.js

I moved back to render.com => we can change back url on front )

CHANGE: move back - changed back url
